
    public enum class D3D10ResourceDimension(value:UInt)
    {
        D3D10_RESOURCE_DIMENSION_UNKNOWN(0.toUInt()),
        D3D10_RESOURCE_DIMENSION_BUFFER(1.toUInt()),
        D3D10_RESOURCE_DIMENSION_TEXTURE1D(2.toUInt()),
        D3D10_RESOURCE_DIMENSION_TEXTURE2D(3.toUInt()),
        D3D10_RESOURCE_DIMENSION_TEXTURE3D(4.toUInt())
    }

